parameters:
    # Adds a fallback DATABASE_URL if the env var is not set.
    # This allows you to run cache:warmup even if your
    # environment variables are not available yet.
    # You should not need to change this value.
    env(DATABASE_URL): ''

doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                driver:   pdo_mysql
                url: '%env(resolve:DEFAULT_DATABASE_URL)%'
                charset:  UTF8
            personal:
                driver:   pdo_mysql
                url: '%env(resolve:PERSONAL_DATABASE_URL)%'
                charset:  UTF8

    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        default_entity_manager: default
        entity_managers:
            default:
                connection: default
                naming_strategy: doctrine.orm.naming_strategy.underscore
                mappings:
                    Main:
                        is_bundle: false
                        type: annotation
                        dir: '%kernel.project_dir%/src/Entity/Main'
                        prefix: 'App\Entity\Main'
                        alias: Main
            personal:
                connection: personal
                naming_strategy: doctrine.orm.naming_strategy.underscore
                mappings:
                    Personal:
                        is_bundle: false
                        type: annotation
                        dir: '%kernel.project_dir%/src/Entity/Personal'
                        prefix: 'App\Entity\Personal'
                        alias: Personal
