language: php
sudo: false
php: 7.2

services:
  - mysql

before_script:
  - composer self-update
  - mysql -e 'CREATE DATABASE tahini;'
  - rm phpunit.xml.dist
  - cp .travis.env .env
  - cp .travis.phpunit.xml.dist phpunit.xml.dist
  - composer install

script:
  - php bin/phpunit