language: php
sudo: false
php: 7.2

services:
  - mysql

before_script:
  - composer self-update
  - mysql -e 'CREATE DATABASE tahini;'
  - cp .travis.env .env
  - cat .env
  - composer install

script:
  - echo "a"