language: php
sudo: false
php: 7.2

services:
  - mysql

env:
  - SCRIPT=travis/cs.sh
  - SCRIPT=travis/phpunit.sh

before_script:
  - composer self-update
  - mysql -e 'CREATE DATABASE tahini;'
  - rm phpunit.xml.dist
  - cp .travis.env .env
  - cp .travis.phpunit.xml.dist phpunit.xml.dist
  - composer install
  - bin/console doctrine:schema:create

script: "bash $SCRIPT"
